### ISSUE TITLE
download of specific course failing every time

### ISSUE THREAD

**Issue by nathanperkins** [FaisalUmair/udemy-downloader-gui#27]
The download of one of my courses is getting stuck every time at 5% and 16 out of 347 items.

![screen shot 2018-01-02 at 5 04 09 pm](https://user-images.githubusercontent.com/10337495/34506185-72933264-efdf-11e7-9673-987cb1d0bb87.png)

I didn't change any settings. I was able to download another course without issues.

![screen shot 2018-01-02 at 5 36 40 pm](https://user-images.githubusercontent.com/10337495/34506628-829ad78a-efe3-11e7-853b-5ddb8f2de669.png)

Let me know if there are any logs that I can provide.

**Comment by FaisalUmair** [comment]
Hi, Thanks for providing the details. 

Can you please attach of screenshot of the course content (specially 16th item) of this course from Udemy.com. I will see whats wrong and push an update. Meanwhile you can just turn off attachment downloads in the settings by checking the "Download Lecture Videos Only" checkbox or you can downgrade to any old version of Udeler.

**Comment by FaisalUmair** [comment]
Never mind, It happens to be a serious bug in v1.3.0. While testing I found most of the courses are getting stuck at some attachment. I have fixed this and updated the repository. However, I haven't released a new version yet. I will update this issue once I release the next version.

**Comment by nathanperkins** [comment]
Great thanks for a quick response :)

**Comment by FaisalUmair** [comment]
Fixed in v1.3.1. Download [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) release.

**Comment by FaisalUmair** [comment]
Assuming v1.3.1 fixed this issue as the courses for which I was able to reproduce this bug are now downloading completely on v1.3.1. 

Closing this issue based on the above assumption. You can reopen the same if the problem is still there.

**Comment by luisuxuk** [comment]
This is still happening in the latest version 1.8.0. (and it happened in the version previous to that one). 

 In most cases the download speed drops to 0, the pause button is deactivated and the download doesn't continue. I have tried deleting the partial course folder and re-starting Udeler, and clicking it to start the download afresh, it resumes and then gets stuck again. Out of 50 courses, it happens to the same 9 courses anywhere and in different computers and networks (home and work).

In some other downloads, 1 out of 50 courses, a download error appears and an option to retry appears but in most cases it just fails again and again.

**Comment by royaldevbrat** [comment]
Same Issue getting in v1.8.0
![image](https://user-images.githubusercontent.com/3677263/75601570-61509080-5ae2-11ea-86c0-d336cde81461.png)

**Comment by jan-far** [comment]
> Same Issue getting in v1.8.0
> ![image](https://user-images.githubusercontent.com/3677263/75601570-61509080-5ae2-11ea-86c0-d336cde81461.png)

yes. the version 1.8.0 is facing the same issue for me. the only thing surprising to me about it is that, it was working well a moment and when i restarted the app, it suddenly doesn't download attachment anymore.

**Comment by Stanley1212** [comment]
> > Mismo problema al obtener v1.8.0
> > ![imagen](https://user-images.githubusercontent.com/3677263/75601570-61509080-5ae2-11ea-86c0-d336cde81461.png)
> 
> si. la versión 1.8.0 enfrenta el mismo problema para mí. Lo único que me sorprende es que funcionó bien un momento y cuando reinicié la aplicación, de repente ya no descarga el archivo adjunto.

Tengo ese mismo problema, ayuda!!!

**Comment by fasilmrm** [comment]
@FaisalUmair i'm facing this issue of freezing while downloading the attachments.. i'm using the latest version of udler. I tried to delete the last file manually, but still facing the problem.. any method to fix it. thanks in advance
![Udler Problem](https://user-images.githubusercontent.com/61681381/75654419-aeb93300-5c85-11ea-86b9-f58fe35dfdad.png)

**Comment by receptektas** [comment]
1.8.0 sürümünde "ATTACHMENT" hatası ile karşılaştım. Uygulamayı 1.8.2 sürümüne güncelleyince sorun geçti. İndirme kaldığı yerden devam etti. İşinize yarayabilir.

**Comment by receptektas** [comment]
1.8.0 karşılaşnde "ATTACHMENT" hatası ile karşılaştım. Uygulamayı 1.8.2 sürümüne izleyineyince sorun geçti. İndirme kaldığı yerden devam etti. İşinize yarayabilir.

**Comment by pulkit2092** [comment]
@FaisalUmair ,i'm facing this issue of freezing while downloading the attachments.. i'm using the latest version of udler. Please give some suggestion to fix this problem. Thanks in advance.

**Comment by utpjafs** [comment]
Me soluciono descargando la ultima versión con el git clone ""  y seguir todas las instrucciones de la documentación para la instalación

**Comment by gokhanyavas** [comment]
geçiçi çözüm : (temporary solution) 

1- indirme klasöründeki son indirmeye gidin
2- ________________python.zip.mtd şeklindeki mtd uzantılı dosyayı bulun. 
3- mtd ekini silip tekrar indirmeyi deneyin. 

Bu şekilde ekleri ve videoları indirmeye devam ediyor. Bunun sebebi eğitmenin yanlış ek yüklemesinden kaynalı bence ;)

**Comment by zerothebahdman** [comment]
> @FaisalUmair ,i'm facing this issue of freezing while downloading the attachments.. i'm using the latest version of udler. Please give some suggestion to fix this problem. Thanks in advance.

I'm also experiencing the same issue. And I'm using the latest version of udeler  v1.8.2.

**Comment by v4jr4** [comment]
hi, i have same issue too, my course stuck on "Building Course Data"...
unfortunately i have 3 courses facing the same issue.  I'm also using udeler v1.8.2.

https://www.udemy.com/course/ultimate-guide-to-digital-sketching-beginner-to-advanced/
https://www.udemy.com/course/character-art-school-complete-character-drawing/
https://www.udemy.com/course/character-art-school-complete-coloring-and-painting/

**Comment by Keshtech2002** [comment]
Hello, i am  also facing similar problem on more than three devices 
It has been the same always 

Downloading get stuck and won't go again for different courses and the network is very good 

Please how can i rectify it #

>

**Comment by Keshtech2002** [comment]
![IMG_20210609_142108_4](https://user-images.githubusercontent.com/66377837/121363388-d25e3500-c92e-11eb-8fc5-9f68876fe839.jpg)
![IMG_20210609_142120_6](https://user-images.githubusercontent.com/66377837/121363582-fde11f80-c92e-11eb-9c47-ae6a9e4cf775.jpg)
![IMG_20210609_142154_8](https://user-images.githubusercontent.com/66377837/121363769-249f5600-c92f-11eb-8080-71a1bd5b5ec7.jpg)

**Comment by iorio87** [comment]
Same probleme here... attachment in every course.

Im using latest version

**Comment by Dave022** [comment]
I am facing the same problem here too on the latest version

**Comment by hatum89** [comment]
I found a solution, I was able to download the course I wanted, but the answer was not to use any code or script, I am wondering how much this information could cost?.

**Comment by hatum89** [comment]
![image](https://user-images.githubusercontent.com/49619672/123540881-d1871a80-d706-11eb-80e6-263b917a72a7.png)

**Comment by ichit** [comment]
@hatum89 please do you mind sharing your fix with, i bought a course i want to watch offline because, i do bot have contant internet

**Comment by zerothebahdman** [comment]
Well what I did to fix my error was to turn off attachments download in settings. So I downloaded the attachments from udemy directly.
