### ISSUE TITLE
Udeler video do not dowloader

### ISSUE THREAD

**Issue by exehakan** [FaisalUmair/udemy-downloader-gui#299]
Hi udemy this morning in the video download process does not download

**Comment by ncesar** [comment]
Its broken.

**Comment by FaisalUmair** [comment]
I have fixed this issue in v1.8.0. You can download the latest version and try again.

Also I have added auto retry option (you can enable it from settings), which will retry the download automatically if it fails.

**Comment by exehakan** [comment]
I'm currently using 1.8 and the problem is still in progress, I've deleted and reinstalled, but no changes

**Comment by exehakan** [comment]
Here You go http://prntscr.com/pxwpoc

**Comment by exehakan** [comment]
or http://prntscr.com/pxwq5f
